# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  syntax='proto3',
  serialized_options=_b('\n\033com.betasolutions.grpc.chatB\tChatProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\nchat.proto\x12\x04\x63hat\"c\n\x0bUserMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0ctext_message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\"b\n\x13ListMessagesRequest\x12\x12\n\ncurrent_id\x18\x01 \x01(\x03\x12\x15\n\rmax_page_size\x18\x02 \x01(\x05\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t2\x88\x01\n\x04\x43hat\x12:\n\x0crealTimeChat\x12\x11.chat.UserMessage\x1a\x11.chat.UserMessage\"\x00(\x01\x30\x01\x12\x44\n\x10listUserMessages\x12\x19.chat.ListMessagesRequest\x1a\x11.chat.UserMessage\"\x00\x30\x01\x42\x30\n\x1b\x63om.betasolutions.grpc.chatB\tChatProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_USERMESSAGE = _descriptor.Descriptor(
  name='UserMessage',
  full_name='chat.UserMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='chat.UserMessage.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='chat.UserMessage.text_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.UserMessage.id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='chat.UserMessage.topic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='chat.UserMessage.client_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=119,
)


_LISTMESSAGESREQUEST = _descriptor.Descriptor(
  name='ListMessagesRequest',
  full_name='chat.ListMessagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_id', full_name='chat.ListMessagesRequest.current_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_page_size', full_name='chat.ListMessagesRequest.max_page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='chat.ListMessagesRequest.topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='chat.ListMessagesRequest.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=219,
)

DESCRIPTOR.message_types_by_name['UserMessage'] = _USERMESSAGE
DESCRIPTOR.message_types_by_name['ListMessagesRequest'] = _LISTMESSAGESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserMessage = _reflection.GeneratedProtocolMessageType('UserMessage', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.UserMessage)
  ))
_sym_db.RegisterMessage(UserMessage)

ListMessagesRequest = _reflection.GeneratedProtocolMessageType('ListMessagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTMESSAGESREQUEST,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ListMessagesRequest)
  ))
_sym_db.RegisterMessage(ListMessagesRequest)


DESCRIPTOR._options = None

_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='chat.Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='realTimeChat',
    full_name='chat.Chat.realTimeChat',
    index=0,
    containing_service=None,
    input_type=_USERMESSAGE,
    output_type=_USERMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listUserMessages',
    full_name='chat.Chat.listUserMessages',
    index=1,
    containing_service=None,
    input_type=_LISTMESSAGESREQUEST,
    output_type=_USERMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
