// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/chat.proto

package com.betasolutions.grpc.chat;

public final class ChatProto {
  private ChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_UserMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_UserMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_ListMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_ListMessagesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025main/proto/chat.proto\022\004chat\"c\n\013UserMes" +
      "sage\022\020\n\010username\030\001 \001(\t\022\024\n\014text_message\030\002" +
      " \001(\t\022\n\n\002id\030\003 \001(\003\022\r\n\005topic\030\004 \001(\t\022\021\n\tclien" +
      "t_id\030\005 \001(\t\"b\n\023ListMessagesRequest\022\022\n\ncur" +
      "rent_id\030\001 \001(\003\022\025\n\rmax_page_size\030\002 \001(\005\022\r\n\005" +
      "topic\030\003 \001(\t\022\021\n\tclient_id\030\004 \001(\t2\210\001\n\004Chat\022" +
      ":\n\014realTimeChat\022\021.chat.UserMessage\032\021.cha" +
      "t.UserMessage\"\000(\0010\001\022D\n\020listUserMessages\022" +
      "\031.chat.ListMessagesRequest\032\021.chat.UserMe" +
      "ssage\"\0000\001B0\n\033com.betasolutions.grpc.chat" +
      "B\tChatProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chat_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_UserMessage_descriptor,
        new java.lang.String[] { "Username", "TextMessage", "Id", "Topic", "ClientId", });
    internal_static_chat_ListMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_ListMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_ListMessagesRequest_descriptor,
        new java.lang.String[] { "CurrentId", "MaxPageSize", "Topic", "ClientId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
