// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/movie.proto

package com.betasolutions.grpc.movie;

/**
 * Protobuf type {@code movie.ListMoviesRequest}
 */
public  final class ListMoviesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:movie.ListMoviesRequest)
    ListMoviesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListMoviesRequest.newBuilder() to construct.
  private ListMoviesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListMoviesRequest() {
    genre_ = "";
    clientId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListMoviesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentId_ = input.readInt64();
            break;
          }
          case 16: {

            maxPageSize_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            genre_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.betasolutions.grpc.movie.MovieProto.internal_static_movie_ListMoviesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.betasolutions.grpc.movie.MovieProto.internal_static_movie_ListMoviesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.betasolutions.grpc.movie.ListMoviesRequest.class, com.betasolutions.grpc.movie.ListMoviesRequest.Builder.class);
  }

  public static final int CURRENT_ID_FIELD_NUMBER = 1;
  private long currentId_;
  /**
   * <code>int64 current_id = 1;</code>
   */
  public long getCurrentId() {
    return currentId_;
  }

  public static final int MAX_PAGE_SIZE_FIELD_NUMBER = 2;
  private int maxPageSize_;
  /**
   * <code>int32 max_page_size = 2;</code>
   */
  public int getMaxPageSize() {
    return maxPageSize_;
  }

  public static final int GENRE_FIELD_NUMBER = 3;
  private volatile java.lang.Object genre_;
  /**
   * <code>string genre = 3;</code>
   */
  public java.lang.String getGenre() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genre_ = s;
      return s;
    }
  }
  /**
   * <code>string genre = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGenreBytes() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object clientId_;
  /**
   * <code>string client_id = 4;</code>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentId_ != 0L) {
      output.writeInt64(1, currentId_);
    }
    if (maxPageSize_ != 0) {
      output.writeInt32(2, maxPageSize_);
    }
    if (!getGenreBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genre_);
    }
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, currentId_);
    }
    if (maxPageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, maxPageSize_);
    }
    if (!getGenreBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genre_);
    }
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.betasolutions.grpc.movie.ListMoviesRequest)) {
      return super.equals(obj);
    }
    com.betasolutions.grpc.movie.ListMoviesRequest other = (com.betasolutions.grpc.movie.ListMoviesRequest) obj;

    if (getCurrentId()
        != other.getCurrentId()) return false;
    if (getMaxPageSize()
        != other.getMaxPageSize()) return false;
    if (!getGenre()
        .equals(other.getGenre())) return false;
    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentId());
    hash = (37 * hash) + MAX_PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxPageSize();
    hash = (37 * hash) + GENRE_FIELD_NUMBER;
    hash = (53 * hash) + getGenre().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.betasolutions.grpc.movie.ListMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.betasolutions.grpc.movie.ListMoviesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code movie.ListMoviesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:movie.ListMoviesRequest)
      com.betasolutions.grpc.movie.ListMoviesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betasolutions.grpc.movie.MovieProto.internal_static_movie_ListMoviesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betasolutions.grpc.movie.MovieProto.internal_static_movie_ListMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betasolutions.grpc.movie.ListMoviesRequest.class, com.betasolutions.grpc.movie.ListMoviesRequest.Builder.class);
    }

    // Construct using com.betasolutions.grpc.movie.ListMoviesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentId_ = 0L;

      maxPageSize_ = 0;

      genre_ = "";

      clientId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.betasolutions.grpc.movie.MovieProto.internal_static_movie_ListMoviesRequest_descriptor;
    }

    @java.lang.Override
    public com.betasolutions.grpc.movie.ListMoviesRequest getDefaultInstanceForType() {
      return com.betasolutions.grpc.movie.ListMoviesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.betasolutions.grpc.movie.ListMoviesRequest build() {
      com.betasolutions.grpc.movie.ListMoviesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.betasolutions.grpc.movie.ListMoviesRequest buildPartial() {
      com.betasolutions.grpc.movie.ListMoviesRequest result = new com.betasolutions.grpc.movie.ListMoviesRequest(this);
      result.currentId_ = currentId_;
      result.maxPageSize_ = maxPageSize_;
      result.genre_ = genre_;
      result.clientId_ = clientId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.betasolutions.grpc.movie.ListMoviesRequest) {
        return mergeFrom((com.betasolutions.grpc.movie.ListMoviesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.betasolutions.grpc.movie.ListMoviesRequest other) {
      if (other == com.betasolutions.grpc.movie.ListMoviesRequest.getDefaultInstance()) return this;
      if (other.getCurrentId() != 0L) {
        setCurrentId(other.getCurrentId());
      }
      if (other.getMaxPageSize() != 0) {
        setMaxPageSize(other.getMaxPageSize());
      }
      if (!other.getGenre().isEmpty()) {
        genre_ = other.genre_;
        onChanged();
      }
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.betasolutions.grpc.movie.ListMoviesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.betasolutions.grpc.movie.ListMoviesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long currentId_ ;
    /**
     * <code>int64 current_id = 1;</code>
     */
    public long getCurrentId() {
      return currentId_;
    }
    /**
     * <code>int64 current_id = 1;</code>
     */
    public Builder setCurrentId(long value) {
      
      currentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_id = 1;</code>
     */
    public Builder clearCurrentId() {
      
      currentId_ = 0L;
      onChanged();
      return this;
    }

    private int maxPageSize_ ;
    /**
     * <code>int32 max_page_size = 2;</code>
     */
    public int getMaxPageSize() {
      return maxPageSize_;
    }
    /**
     * <code>int32 max_page_size = 2;</code>
     */
    public Builder setMaxPageSize(int value) {
      
      maxPageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_page_size = 2;</code>
     */
    public Builder clearMaxPageSize() {
      
      maxPageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object genre_ = "";
    /**
     * <code>string genre = 3;</code>
     */
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder setGenre(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      genre_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder clearGenre() {
      
      genre_ = getDefaultInstance().getGenre();
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder setGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      genre_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 4;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 4;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 4;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 4;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:movie.ListMoviesRequest)
  }

  // @@protoc_insertion_point(class_scope:movie.ListMoviesRequest)
  private static final com.betasolutions.grpc.movie.ListMoviesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.betasolutions.grpc.movie.ListMoviesRequest();
  }

  public static com.betasolutions.grpc.movie.ListMoviesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListMoviesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListMoviesRequest>() {
    @java.lang.Override
    public ListMoviesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListMoviesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListMoviesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListMoviesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.betasolutions.grpc.movie.ListMoviesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

