// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/movie.proto

package com.betasolutions.grpc.movie;

public interface ListMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.ListMoviesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 current_id = 1;</code>
   */
  long getCurrentId();

  /**
   * <code>int32 max_page_size = 2;</code>
   */
  int getMaxPageSize();

  /**
   * <code>string genre = 3;</code>
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>string client_id = 4;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
