// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/movie.proto

package com.betasolutions.grpc.movie;

public interface MovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.Movie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string movie_name = 2;</code>
   */
  java.lang.String getMovieName();
  /**
   * <code>string movie_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getMovieNameBytes();

  /**
   * <code>string genre = 3;</code>
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>string client_id = 4;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
