# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='movie',
  syntax='proto3',
  serialized_options=_b('\n\034com.betasolutions.grpc.movieB\nMovieProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x0bmovie.proto\x12\x05movie\"I\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nmovie_name\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"`\n\x11ListMoviesRequest\x12\x12\n\ncurrent_id\x18\x01 \x01(\x03\x12\x15\n\rmax_page_size\x18\x02 \x01(\x05\x12\r\n\x05genre\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t2\x86\x01\n\x0cMovieLibrary\x12<\n\x18getAndUpdateMovieLibrary\x12\x0c.movie.Movie\x1a\x0c.movie.Movie\"\x00(\x01\x30\x01\x12\x38\n\nlistMovies\x12\x18.movie.ListMoviesRequest\x1a\x0c.movie.Movie\"\x00\x30\x01\x42\x32\n\x1c\x63om.betasolutions.grpc.movieB\nMovieProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='movie.Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='movie.Movie.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='movie_name', full_name='movie.Movie.movie_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='movie.Movie.genre', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='movie.Movie.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=95,
)


_LISTMOVIESREQUEST = _descriptor.Descriptor(
  name='ListMoviesRequest',
  full_name='movie.ListMoviesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_id', full_name='movie.ListMoviesRequest.current_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_page_size', full_name='movie.ListMoviesRequest.max_page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='movie.ListMoviesRequest.genre', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='movie.ListMoviesRequest.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.message_types_by_name['ListMoviesRequest'] = _LISTMOVIESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(
  DESCRIPTOR = _MOVIE,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.Movie)
  ))
_sym_db.RegisterMessage(Movie)

ListMoviesRequest = _reflection.GeneratedProtocolMessageType('ListMoviesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTMOVIESREQUEST,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.ListMoviesRequest)
  ))
_sym_db.RegisterMessage(ListMoviesRequest)


DESCRIPTOR._options = None

_MOVIELIBRARY = _descriptor.ServiceDescriptor(
  name='MovieLibrary',
  full_name='movie.MovieLibrary',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=196,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAndUpdateMovieLibrary',
    full_name='movie.MovieLibrary.getAndUpdateMovieLibrary',
    index=0,
    containing_service=None,
    input_type=_MOVIE,
    output_type=_MOVIE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listMovies',
    full_name='movie.MovieLibrary.listMovies',
    index=1,
    containing_service=None,
    input_type=_LISTMOVIESREQUEST,
    output_type=_MOVIE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVIELIBRARY)

DESCRIPTOR.services_by_name['MovieLibrary'] = _MOVIELIBRARY

# @@protoc_insertion_point(module_scope)
